### ISSUE TITLE
Add Auth

### ISSUE THREAD

**Issue by remib18** [remib18/symfony-video#3]
Add a basic authentication to the app.

## Tasks

- [x] Setup user entity (`firstname`, `lastname`, `imageLink`, `email`, `isBanned`) with `make:user`
- [x] Authentication forms (login ; register) with `make:auth` and `make:registration-form`
- [x] Add a /app route that users get redirected on login
- [x] Enable access_control in security config (three profiles : `ROLE_USER` ; `ROLE_WEBMASTER` and `ROLE_ADMIN`)

## ER-Model

For a reminder, here is the ER-Model we agreed on.
![Image](https://github.com/remib18/symfony-video/assets/74245760/d59fdbd8-01bc-489a-8505-44ddf63fda6d)
