### ISSUE TITLE
Create the homepage

### ISSUE THREAD

**Issue by remib18** [remib18/symfony-video#5]
Build a basic homepage.

## Tasks

- [x] `composer require league/commonmark` (see: [the documentation](https://commonmark.thephpleague.com/2.4/))
- [x] Create the entity `WebsiteSettings`
- [x] Create the entity `HomePages`
- [x] Use the above library to load `homepageMD`
- [ ] Add an admin page to manage this data
- [x] Plan some space for last tree blog post.
- [x] Plan some space for a contact form

## ER-Model

For remember, here the ER-Model we agreed on.

![Image](https://github.com/remib18/symfony-video/assets/118015442/c82098b5-0107-4d5c-bca2-50520337c1d4)
