### ISSUE TITLE
Blog system

### ISSUE THREAD

**Issue by remib18** [remib18/symfony-video#7]
Implementing a basic blog system.

## Tasks

- [ ] Create the entity
- [ ] Adding in the dashboard the option to manage the blog posts (for webmasters and admins only)
- [ ] Add on the homepage the last tree posted blogs.

## ER-Model

For reminder, here the ER-Model we agreed on.
![Image]

![Image](https://github.com/remib18/symfony-video/assets/118015442/4d28a62e-4469-4056-adfb-37cd077199b5)
