### ISSUE TITLE
Contact system

### ISSUE THREAD

**Issue by remib18** [remib18/symfony-video#8]
Implement a basic contact system.

## Tasks

- [x] Create the corresponding entity
- [x] Add a contact form in the planned zone in the homepage
- [x] Add an admin management for this entity (fetch, delete)
- [x] Add an answer action (link with mailto — see: [w3docs](https://www.w3docs.com/snippets/html/how-to-create-mailto-links.html))

## ER-Model

For a reminder, here is the ER-Model we agreed on.

![Image](https://github.com/remib18/symfony-video/assets/118015442/d0aed345-ce02-40e3-b17f-a204f0495cc4)
