### ISSUE TITLE
Film Research feature

### ISSUE THREAD

**Issue by remib18** [remib18/symfony-video#9]
The end goal is to be able to save medias to the database in order to be able to build a research feature.

Implement the movie / tv-show / anime... search feature.

In order to simplify, we will shorten movie / tv-show... by movies.

## Tasks

- [x] Implement entities ImDBEntry ; Category and Episode
- [x] Add a field to search for a movies
- [x] Implement the search
- [x] Display the result accordingly

The search should first try to find the result on the database and then, if not found, search on the ImDB database. If found in the ImDB database, the data should be persisted in the database.

## ER-Model

For a reminder, here is the ER-Model we agreed on.

![Image](https://github.com/remib18/symfony-video/assets/118015442/d0aed345-ce02-40e3-b17f-a204f0495cc4)
